### ISSUE TITLE
Hardware disable HDMI

### ISSUE THREAD

**Issue by Paffo** [DesobedienteTecnologico/rpi_disable_wifi_and_bt_by_hardware#2]
Hello,
Thanks for your guide, i was wondering if it's possible to do the same but with the HDMI port.
Mine fried due to ESD and is not working anymore.
The rest of the Pi Zero W works well, but overheats a lot, i suspect due to a short in one of the downstream components.
Do you know what is the highest (closest to BCM) way to disable this port?

Thanks

**Comment by DesobedienteTecnologico** [comment]
Hi, I'm sorry to say that I don't really know how to approach that. But probably having a look to the x-ray images will give you a clue.

At the end, you will have to test the components and do desolder-solder work... Probably you expend less money/time buying a new one.

Regards

![image](https://github.com/DesobedienteTecnologico/rpi_disable_wifi_and_bt_by_hardware/assets/52879067/884b40ec-1652-4430-b0df-a5b2513a7491)
